apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lms-portal-hpa
  namespace: lms-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lms-portal-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70      # CPU 70% होते ही अपने आप नए Pods बन जाएंगे

